name: Quests
author: birthdates
version: 1.0.0
main: com.birthdates.quests.QuestPlugin
api-version: 1.17
commands:
  quest:
    aliases: [ quests, q ]
  language:
    aliases: [ lang ]
#permissions:
#  quests.admin:
#    description: Language menu command
#    default: false